import { motion } from "framer-motion";
import { AlertCircle } from "lucide-react";
import SectionPadding from "@/layouts/SectionPadding";

export default function DisclaimerSection() {
  return (
    <SectionPadding className="py-12 relative overflow-hidden">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        className="relative bg-[#0A0D11]/40 backdrop-blur-3xl border border-white/5 rounded-[32px] p-8 md:p-12 overflow-hidden group"
      >
        {/* Subtle Background Technical Grid */}
        <div className="absolute inset-0 opacity-[0.02] pointer-events-none" 
             style={{ backgroundImage: `radial-gradient(circle at 2px 2px, white 1px, transparent 0)`, backgroundSize: '24px 24px' }} />
        
        <div className="flex flex-col md:flex-row items-start md:items-center gap-8 relative z-10">
          <div className="w-14 h-14 rounded-2xl bg-white/5 border border-white/10 flex items-center justify-center shrink-0 group-hover:border-primary/30 transition-colors duration-500">
            <AlertCircle className="w-7 h-7 text-white/20 group-hover:text-primary transition-colors" />
          </div>

          <div className="flex-1 space-y-4">
            <div className="flex items-center gap-3">
              <h4 className="text-lg font-black text-white uppercase tracking-tighter italic leading-none">
                Legal Advisory <span className="text-primary/80">& Usage Transparency</span>
              </h4>
              <div className="hidden md:block h-px flex-1 bg-white/5" />
            </div>

            <p className="text-white/40 text-sm font-medium leading-relaxed max-w-4xl">
              SharpToolz is a high-fidelity document generation platform engineered for 
              <span className="text-white/60 mx-1">Rapid Content Creation</span>, 
              <span className="text-white/60 mx-1">App Testing</span>, and 
              <span className="text-white/60 mx-1">Digital Demonstrations</span>. 
              Outputs generated by these tools are for informational and simulation purposes only. 
              We do not provide legal, financial, or professional advice. Users are responsible 
              for ensuring compliance with local jurisdiction regulations.
            </p>
          </div>
        </div>
      </motion.div>
    </SectionPadding>
  );
}
